#!usr/bin/sh

cd consola
make clean
make
cd ..

cd cpu
make clean
make
cd ..

cd nucleo
make clean
make
cd ..

cd swap
make clean
make
cd ..

cd umc
make clean
make
cd ..

echo ""
echo "Se compilaron los 5 modulos."
