#!usr/bin/sh

clear

cd consola
cd Debug
make clean
make all
cd ..
cd ..

cd cpu
cd Debug
make clean
make all
cd ..
cd ..

cd nucleo
cd Debug
make clean
make all
cd ..
cd ..

cd swap
cd Debug
make clean
make all
cd ..
cd ..

cd umc
cd Debug
make clean
make all
cd ..
cd ..

echo ""
echo "Se compilaron los 5 modulos."
