#!usr/bin/sh


cd consola
cd Debug
cd code
sed -i 's/\/home\/utnso\/workspace\/tp-2016-1c-Con-16-bits-me-hago-alto-kernel/\.\.\/\.\./g' subdir.mk
cd ..
cd ..
cd ..

cd cpu
cd Debug
cd code
sed -i 's/\/home\/utnso\/workspace\/tp-2016-1c-Con-16-bits-me-hago-alto-kernel/\.\.\/\.\./g' subdir.mk
cd ..
cd ..
cd ..

cd nucleo
cd Debug
cd code
sed -i 's/\/home\/utnso\/workspace\/tp-2016-1c-Con-16-bits-me-hago-alto-kernel/\.\.\/\.\./g' subdir.mk
cd ..
cd ..
cd ..

cd swap
cd Debug
cd code
sed -i 's/\/home\/utnso\/workspace\/tp-2016-1c-Con-16-bits-me-hago-alto-kernel/\.\.\/\.\./g' subdir.mk
cd ..
cd ..
cd ..

cd umc
cd Debug
cd code
sed -i 's/\/home\/utnso\/workspace\/tp-2016-1c-Con-16-bits-me-hago-alto-kernel/\.\.\/\.\./g' subdir.mk
cd ..
cd ..
cd ..

echo "Fix aplicado"
